// <auto-generated />
namespace Shelterly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Removedstringlengthfromdescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removedstringlengthfromdescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201903212312417_Removed string length from description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
